#!/usr/bin/env bash

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload main &
done

feh --bg-fill ~/Images/c-base-hackerspace-berlin.jpg

i3-msg '[class="Google-chrome"]' move to workspace 1
