#!/usr/bin/env bash

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload main &
done

feh --bg-fill ~/Images/Wallpapers/techno-alley-cyber.jpg

i3-msg '[workspace="1"]' move workspace to output eDP-1 &
i3-msg '[workspace="2"]' move workspace to output HDMI-2 &
i3-msg '[workspace="3"]' move workspace to output HDMI-2 &
i3-msg '[workspace="4"]' move workspace to output HDMI-2 &
i3-msg '[workspace="5"]' move workspace to output HDMI-2 &
i3-msg '[workspace="6"]' move workspace to output HDMI-2 &
i3-msg '[workspace="7"]' move workspace to output HDMI-2 &
i3-msg '[workspace="8"]' move workspace to output HDMI-2 &
i3-msg '[workspace="9"]' move workspace to output HDMI-2 &

i3-msg '[class="Google-chrome"]' move to workspace 2
